# Generated by Django 2.1.3 on 2018-11-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('api', '0001_initial'), ('api', '0002_auto_20181118_1557'), ('api', '0003_auto_20181118_1617'), ('api', '0004_auto_20181118_1726'), ('api', '0005_auto_20181119_0914'), ('api', '0006_auto_20181120_1345'), ('api', '0007_auto_20181120_1352'), ('api', '0008_auto_20181120_1352')]

    initial = True

    dependencies = [
    ]

    operations = [
    ]
