# Generated by Django 2.1.3 on 2018-11-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foo',
            field=models.BooleanField(null=True),
        ),
    ]
