# Generated by Django 2.1.4 on 2018-12-18 14:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('base', '0002_auto_20181217_1236'), ('base', '0003_auto_20181217_1239'), ('base', '0004_auto_20181218_1420'), ('base', '0005_auto_20181218_1545')]

    dependencies = [
        ('base', '0001_squashed_0002_auto_20181211_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Message',
            old_name='created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='Message',
            old_name='updated',
            new_name='date_updated',
        ),
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_updated',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date_created']},
        ),
    ]
