# Generated by Django 2.1.3 on 2018-11-21 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_foo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='foo',
        ),
        migrations.AlterField(
            model_name='message',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='username', to='base.User'),
        ),
    ]
